name: Windows - RDP

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Downloads.bat from local repository
        run: cmd /c Downloads.bat

      - name: Enabling RDP on Windows
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Setting up the RDP connection
        run: |
          mstsc /v:your_rdp_server_ip

      - name: Time Counter
        run: cmd /c loop.bat
